[workspace]
name = "snakemake-wrf-wps-compilation"
version = "0.3.1"
description = "Snakemake workflow to compile WRF/WPS over EESSI using EasyBuild"
authors = ["Pablo Orviz <orviz@ifca.es>", "Valvanuz Fernández <valvanuz.fernandez@unican.es"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.10"
conda = "*"

# --- SnakeMake ecosystem 8+ ---
snakemake = ">=8.0"
snakemake-executor-plugin-slurm = "*"

tcsh = "*"

[tasks]
# Local
dry-run   = "snakemake --dry-run --profile"
run-local = "snakemake --cores 1"
# Generic Slurm
run-slurm = "snakemake --profile"
# HPC profiles
hpc-profile = "bash -c 'PROFILE=$1; PROFILE_DIR=\"config/profiles/$PROFILE\"; ENV_SCRIPT=\"$PROFILE_DIR/set-env.sh\"; if [ -d \"$PROFILE_DIR\" ]; then if [ -f \"$ENV_SCRIPT\" ]; then source \"$ENV_SCRIPT\"; fi && snakemake --profile \"$PROFILE_DIR\" \"${@:2}\"; else echo \"Error: HPC profile \\'$PROFILE\\' not found under config/profiles/\"; exit 1; fi' --"
