#!/usr/bin/bash
# workflow/scripts/compile.sh
set -euo pipefail

# =========================================================================
# 1. PARSE SNAKEMAKE INPUT PARAMETERS
# =========================================================================
EESSI_INIT_SCRIPT="$1"
STATUS_JSON="$2"
LOCAL_RECIPE_PATH="$3"
MARKER_DIR="$4"
MARKER_ABS_PATH="$5"

# =========================================================================
# 2. DYNAMIC METADATA EXTRACTION FROM JSON (HPC-Safe using Python)
# =========================================================================
# Extract status, software name, and target recipe natively from the JSON report
STATUS=$(python3 -c "import json; print(json.load(open('$STATUS_JSON'))['status'])")
RECIPE_TARGET=$(python3 -c "import json; print(json.load(open('$STATUS_JSON'))['recipe_target'])")
SOFTWARE_NAME=$(python3 -c "import json; print(json.load(open('$STATUS_JSON'))['software'])")

# =========================================================================
# 3. ISOLATED AND STERILE INITIALIZATION OF THE EESSI STACK
# =========================================================================
set +u
source "$EESSI_INIT_SCRIPT"
module load EESSI-extend
set -u

# Core threading and memory mitigation flags for subprocess scheduling
export OPENBLAS_NUM_THREADS=1
export FLEXIBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
ulimit -s unlimited

# =========================================================================
# 4. ALGORITHMIC BUILD DECISION (Bypassing EESSI Hooks Restriction)
# =========================================================================
if [ "$STATUS" == "EESSI_OFFICIAL" ]; then
    echo "[Compiler] Tuning to OFFICIAL mode. Using EESSI native recipe: $RECIPE_TARGET"
    
    eb "$RECIPE_TARGET" \
      --robot \
      --local-var-naming-check=warn \
      --skip-test-step \
      --detect-loaded-modules=purge \
      --force
else
    echo "[Compiler] Tuning to LOCAL FALLBACK mode. Injecting custom recipe and patches..."
    PATCH_DIR=$(dirname "$LOCAL_RECIPE_PATH")
    
    eb "$LOCAL_RECIPE_PATH" \
      --robot \
      --local-var-naming-check=warn \
      --skip-test-step \
      --detect-loaded-modules=purge \
      --ignore-checksums \
      --patches-path="$PATCH_DIR" \
      --force
fi

# =========================================================================
# 5. DYNAMIC DISCOVERY OF THE ACTUAL INSTALLATION PATH (Option 1)
# =========================================================================
# Rely on EasyBuild native environment variable to resolve the target destination prefix
INSTALL_PATH="${EASYBUILD_INSTALLPATH:-$HOME/eessi/versions/2025.06/software/linux/x86_64}"

echo "[Compiler] Scanning for real binary assets within dynamic path: $INSTALL_PATH"

# Physically locate the successful output executables generated by the build matrix
REAL_WRF=$(find "$INSTALL_PATH" -type f -name "wrf.exe" | head -n 1)
REAL_UNGRIB=$(find "$INSTALL_PATH" -type f -name "ungrib.exe" | head -n 1)

# Ensure the local repository binary target tree directory exists
mkdir -p "$MARKER_DIR"

# Synchronize physical success metrics by deploying clean repository symlinks
if [ "$SOFTWARE_NAME" == "WPS" ] && [ -n "$REAL_UNGRIB" ]; then
    echo " -> [OK] WPS binary located at: $REAL_UNGRIB"
    ln -sf "$REAL_UNGRIB" "$MARKER_ABS_PATH"
elif [ "$SOFTWARE_NAME" == "WRF" ] && [ -n "$REAL_WRF" ]; then
    echo " -> [OK] WRF binary located at: $REAL_WRF"
    ln -sf "$REAL_WRF" "$MARKER_ABS_PATH"
else
    echo "❌ [Error] Sanity Check crashed: No functional binaries discovered in $INSTALL_PATH"
    exit 1
fi

echo "[Compiler Success] Local production symlink successfully established at: $MARKER_ABS_PATH"
