---

wrf_version: "4.6.1"
wps_version: "4.6.0"

# These variables can be overridden and will be only used when running the compilation directly.
wps_install_dir: "WPS"
wrf_install_dir: "WRF"

installation_engine: "easybuild"

easybuild:
  toolchain_name: "foss" # toolchain name (e.g., foss, intel, etc.)
  toolchain_version: "2024a" # toolchain version (e.g., 2024a, 2023b, etc.)
  toolchain_type: "dmpar" # toolchain type (e.g., dmpar, serial, etc.)

  wps_subdir: "software/WPS/{wps_version}-{toolchain_name}-{toolchain_version}-{toolchain_type}/WPS-{wps_version}"
  wrf_subdir: "software/WRF/{wrf_version}-{toolchain_name}-{toolchain_version}-{toolchain_type}/WRFV{wrf_version}"

eessi_init_script: "/cvmfs/software.eessi.io/versions/2025.06/init/bash"