# WPS configuration for WRF compilation and execution
wps_version: "v4.6.0"
wps_configure_option: "3" # foss-dmpar option (GRIB2 enabled)

# Local installation path
install_root: "/home/user/sw/WPS-v4.6.0"
jasper_version: "1.900.1"
jasper_download_url: "https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/jasper-1.900.1.tar.gz"

# EESSI (CVMFS) environment settings for WRF compilation and execution
eessi_init_script: "/cvmfs/software.eessi.io/versions/2025.06/init/bash"
eessi_wrf_module: "WRF/4.6.1-foss-2024a-dmpar"
eessi_wrf_dir: "/cvmfs/software.eessi.io/versions/2025.06/software/linux/x86_64/intel/cascadelake/software/WRF/4.6.1-foss-2024a-dmpar/WRFV4.6.1"